### ISSUE TITLE
Look at trash

### ISSUE THREAD

**Issue by sdsanders** [petdance/altbox#23]
`trash` is a safer alternative for `rm`, which moves file into the trash or recycle bin rather than permanently deleting them.

https://github.com/sindresorhus/trash-cli

**Comment by petdance** [comment]
Thanks for the suggestion.  It's in my queue now.

**Comment by petdance** [comment]
Done.  Thank you.

b69fc54262f25acea1d1e07ebfdd0a9b3e4e8be9

https://altbox.dev/trash/
