### ISSUE TITLE
Add atop

### ISSUE THREAD

**Issue by NHOrus** [petdance/altbox#34]
As top replacement.
Does not have graphics, instead shows network, disk, processor and memory usage/load, has ability to sort processes by most load/bottleneck, be it CPU, disk or memory.

**Comment by NHOrus** [comment]
![atop](https://user-images.githubusercontent.com/5390835/56232222-ec6e9680-6088-11e9-8381-4b07132e67f8.png)
screenshot

**Comment by petdance** [comment]
Added.  Thank you!

https://altbox.dev/atop/
