### ISSUE TITLE
Menu button on mobile not behaving like expected

### ISSUE THREAD

**Issue by smonff** [petdance/altbox#64]
Hi, 

it looks like the menu button in the navigation bar is dysfunctionning ~~on mobile browsers~~ on low width screen mode. 

When clicked, nothing happen.

Reproductible on mobile versions of Chrome, Firefox, Brave plus Firefox desktop.

**Comment by smonff** [comment]
I investigated a bit and it looks like `https://altbox.dev/assets/js/just-the-docs.js` returns HTML, that seems abnormal. 

The issue is reproducible on desktop browsers, as long as you are in low width screen mode.

**Comment by petdance** [comment]
Thanks, I'm looking into it.

**Comment by petdance** [comment]
It looks like version 0.2.6 of https://github.com/pmarsceill/just-the-docs tries to build the site HTML into the just-the-docs.js file.  I've rolled back to requiring 0.2.5.  How does it look now?

**Comment by smonff** [comment]
It works!
