### ISSUE TITLE
Add bottom (`top` alternative)

### ISSUE THREAD

**Issue by cherryblossom000** [petdance/altbox#86]
https://github.com/ClementTsang/bottom

> A cross-platform graphical process/system monitor with a customizable interface and a multitude of features.

It also shows disk usage information, so could it could be an alternative for `df` as well.

![](https://raw.githubusercontent.com/ClementTsang/bottom/master/assets/demo.gif)

**Comment by petdance** [comment]
Added to https://altbox.dev/bottom/

Thanks for providing the screenshots etc.  This makes it much easier to add stuff.
